apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  labels:
    omponent: user
    project: roboshop
    tier: app
data:
  MONGO: "true"  
  REDIS_URL: "redis://redis:6379" 
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  # deployment labels
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  replicas: 2
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  # This is pod definition to create # here metadata name not given 
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: lvnaren532/user:v1  # it will pull form dcoker hub
        envFrom:
        - configMapRef: 
            name: user

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:  #so the Service will route traffic to this ,Pod which haveing the same lables
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080  # service port
      targetPort: 8080 # container port